# NOTE: In contrast to Linux and macOS, the Windows build machines do not have Chrome installed.

name: "HTML2PDF4Doc on Windows"

on:
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Google Chrome
      run: |
        choco install googlechrome --no-progress -y --ignore-checksums
      shell: powershell

    - name: Check Chrome Version
      run: '(Get-Item "C:\Program Files\Google\Chrome\Application\chrome.exe").VersionInfo'
      shell: powershell

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install minimal Python packages
      run: |
        pip install -r requirements.development.txt

    - name: Clone HTML2PDF4Doc.js
      run: |
        invoke bootstrap

    - name: Install HPDF dependencies.
      run: |
        python developer/pip_install_html2pdf4doc_deps.py

    - name: Run Lint tasks
      run: |
        invoke lint

    - name: Build HTML2PDF4Doc.js
      run: |
        invoke build

    - name: Download ChromeDriver
      run: |
        python html2pdf4doc/html2pdf4doc.py get_driver

    - name: Run tests (Bash)
      run: |
        invoke test
      shell: bash
